export type DocType =
  | "Go-To-Market Plan"
  | "Product Roadmap"
  | "OKR Framework"
  | "Competitive Analysis"
  | "Marketing Strategy"
  | "Brand Guidelines"
  | "Content Strategy"
  | "Business Case"
  | "General Strategy";

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
  docRef?: string; // ID of a document generated by this message
}

export interface StrategyDoc {
  id: string;
  title: string;
  type: DocType;
  content: string;
  chatHistory: ChatMessage[];
  createdAt: Date;
  updatedAt: Date;
  wordCount: number;
}

const GOLD_BADGE = "bg-[var(--gold-primary)]/10 text-[var(--gold-primary)] border-[var(--gold-primary)]/20";
const GOLD_BAR   = "from-[var(--gold-primary)]/50 via-[var(--gold-primary)]/15 to-transparent";
const GOLD_ICON  = "text-[var(--gold-primary)]";

export const TYPE_STYLES: Record<DocType, { badge: string; bar: string; icon: string }> = {
  "Go-To-Market Plan":    { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "Product Roadmap":      { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "OKR Framework":        { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "Competitive Analysis": { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "Marketing Strategy":   { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "Brand Guidelines":     { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "Content Strategy":     { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "Business Case":        { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
  "General Strategy":     { badge: GOLD_BADGE, bar: GOLD_BAR, icon: GOLD_ICON },
};
